module.exports = {
    CSColorReset: "\x1b[0m",
    CSColorBright: "\x1b[1m",
    CSColorDim: "\x1b[2m",
    CSColorUnderscore: "\x1b[4m",
    CSColorBlink: "\x1b[5m",
    CSColorReverse: "\x1b[7m",
    CSColorHidden: "\x1b[8m",
    CSColorFgBlack: "\x1b[30m",
    CSColorFgRed: "\x1b[31m",
    CSColorFgGreen: "\x1b[32m",
    CSColorFgYellow: "\x1b[33m",
    CSColorFgBlue: "\x1b[34m",
    CSColorFgMagenta: "\x1b[35m",
    CSColorFgCyan: "\x1b[36m",
    CSColorFgWhite: "\x1b[37m",
    CSColorBgBlack: "\x1b[40m",
    CSColorBgRed: "\x1b[41m",
    CSColorBgGreen: "\x1b[42m",
    CSColorBgYellow: "\x1b[43m",
    CSColorBgBlue: "\x1b[44m",
    CSColorBgMagenta: "\x1b[45m",
    CSColorBgCyan: "\x1b[46m",
    CSColorBgWhite: "\x1b[47m"
};